version: "3.9"

services:

    postgres:
        image: ${REPO_PG}
        container_name: ${PG_HOST}
        ports: 
          - 5433:${PG_PORT}
        environment:
            POSTGRES_HOST: ${PG_HOST}
            POSTGRES_USER: ${PG_USER} 
            POSTGRES_PASSWORD: ${PG_PASS}
            POSTGRES_DB: ${PG_DB}
        volumes:
          - ./data/postgres-db-volume:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-U", "${PG_USER}"]
            interval: 5s
            retries: 5
        restart: always
    
    fastapi:
        depends_on:
            postgres:
                condition: service_healthy
        build: .
        container_name: ${FASTAPI_HOST}
        ports:
          - ${FASTAPI_PORT}:${FASTAPI_PORT_DOCKER}
        volumes:
          - ./api:/usr/src/app
        environment:
            NAME: ${NAME}
            POSTGRES_HOST: ${PG_HOST}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASS}
            POSTGRES_DB: ${PG_DB}
        healthcheck:
            test: ["CMD", "curl", "-f", "http://${FASTAPI_HOST}:${FASTAPI_PORT_DOCKER}/health"]
            interval: 60s
            retries: 3
        restart: unless-stopped

